import type { IconType } from 'react-icons'
import {
  SiPython,
  SiMysql,
  SiHtml5,
  SiCss3,
  SiReact,
  SiNodedotjs,
  SiVite,
  SiSupabase,
  SiDocker,
  SiPandas,
  SiNumpy,
  SiScikitlearn,
  SiTensorflow,
  SiJupyter,
  SiHuggingface,
  SiOpenai,
  SiKaggle,
  SiGooglescholar,
  SiGooglemaps,
  SiGit,
  SiGithub,
  SiVisualstudiocode,
  SiGooglecolab,
  SiAmazonwebservices,
} from 'react-icons/si'
import { FaBolt, FaFileWord, FaFileExcel, FaBrain, FaSpider, FaPlug } from 'react-icons/fa'

export const toolIcons: Record<string, IconType> = {
  python: SiPython,
  sql: SiMysql,
  html: SiHtml5,
  css: SiCss3,
  react: SiReact,
  reactnative: SiReact,
  nodejs: SiNodedotjs,
  vite: SiVite,
  supabase: SiSupabase,
  docker: SiDocker,
  ml: FaBrain,
  dl: FaBrain,
  pandas: SiPandas,
  numpy: SiNumpy,
  scikitlearn: SiScikitlearn,
  tensorflow: SiTensorflow,
  jupyter: SiJupyter,
  huggingface: SiHuggingface,
  openenv: FaPlug,
  aitools: SiOpenai,
  kaggle: SiKaggle,
  apollo: FaSpider,
  parsehub: FaSpider,
  instantscraper: FaSpider,
  scholar: SiGooglescholar,
  googlemaps: SiGooglemaps,
  websockets: FaBolt,
  git: SiGit,
  github: SiGithub,
  vscode: SiVisualstudiocode,
  word: FaFileWord,
  excel: FaFileExcel,
  colab: SiGooglecolab,
  aws: SiAmazonwebservices,
}
